apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstore
  template:
    metadata:
      labels:
        app: eventstore
    spec:
      containers:
        - name: eventstore
          image: eventstore/eventstore
          env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: '1'
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: 'All'
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: 'true'
            - name: EVENTSTORE_EXT_TCP_PORT
              value: '1113'
            - name: EVENTSTORE_HTTP_PORT
              value: '2113'
            - name: EVENTSTORE_INSECURE
              value: 'true'
            - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
              value: 'true'
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: 'true'
          ports:
            - containerPort: 1113
            - containerPort: 2113
---
apiVersion: v1
kind: Service
metadata:
  name: eventstore-srv
spec:
  selector:
    app: 'eventstore'
  ports:
    - name: client
      protocol: 'TCP'
      port: 2113
      targetPort: 2113
  clusterIP: None
